
toolchainUrl.FREE_BSD.AARCH64=https\:
toolchainUrl.FREE_BSD.X86_64=https\:
toolchainUrl.LINUX.AARCH64=https\:
toolchainUrl.LINUX.X86_64=https\:
toolchainUrl.MAC_OS.AARCH64=https\:
toolchainUrl.MAC_OS.X86_64=https\:
toolchainUrl.UNIX.AARCH64=https\:
toolchainUrl.UNIX.X86_64=https\:
toolchainUrl.WINDOWS.AARCH64=https\:
toolchainUrl.WINDOWS.X86_64=https\:
toolchainVersion=21

